name: CI/CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.12"
            
            - name: Install Dependencies
              run: |
                cd MLOps/container
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r requirements.txt

            - name: Run pytest
              run: |
                cd MLOps/container
                pytest


