name: CI/CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.12"
            
            - name: Install Dependencies
              run: | 
                cd container
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r requirements.txt

            - name: Run pytest
              run: |
                cd container
                pytest
# 1. .github/workflows must be in root directory so github action can auto track it
# 2. it will track any changes made in entire repo
# 3. path changed by cd is just to show where commands needs to be run wrt to presence of other files
# like our app file etc. But it tracks any changes in antire repo.

